# Generated by Django 6.0.6 on 2026-07-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('telegram', 'Telegram'), ('portfolio', 'Portfolio / Website'), ('behance', 'Behance'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resumes.resume')),
            ],
        ),
    ]
