# Generated by Django 6.0.6 on 2026-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_certification_language_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Опис'),
        ),
    ]
