# Generated by Django 6.0.6 on 2026-07-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='resumes.resume'),
        ),
    ]
