# Generated by Django 5.2.16 on 2026-07-12 20:33

import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_certification_id_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=resumes.models.user_directory_path),
        ),
    ]
