# Generated by Django 5.2.16 on 2026-07-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_personalinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('None', ''), ('Novice', 'Новачок'), ('Advanced Beginner', 'Початківець-практик'), ('Competent', 'Компетентний'), ('Proficient', 'Професіонал'), ('Expert', 'Експерт')], max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume')),
            ],
        ),
    ]
