# Generated by Django 5.2.16 on 2026-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_skills_options_education_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
