# Generated by Django 5.2.16 on 2026-07-14 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_alter_education_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
