# Generated by Django 5.2.16 on 2026-07-22 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_resume_is_public_resume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.CharField(default='UA', max_length=4, verbose_name='Мова шаблону'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
    ]
