name: Deploy CVForge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync Files
        run: |
          cd /var/www/cvforge-source/
          git fetch origin main
          git reset --hard origin/main
          git clean -fd
      
         

      - name: Deploy Backend
        run: |
          rsync -av --delete --exclude='.venv/' --exclude='.env' /var/www/cvforge-source/backend/ /var/www/cvforgebackend/ || true
          cd /var/www/cvforgebackend/
          .venv/bin/pip3 install -r requirements.txt
          .venv/bin/python3 manage.py migrate
          sudo systemctl restart cvforgeapi

      - name: Deploy Frontend
        run: |
          rsync -av --delete /var/www/cvforge-source/frontend/ /var/www/cvforge/ || true
          cd /var/www/cvforge/
          sudo systemctl restart nginx
