name: Deploy CVForge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync and Deploy
        run: |
          cd /var/www/cvforge-source/
          git pull origin main
          
          rsync -av --delete /var/www/cvforge-source/backend/ /var/www/cvforgebackend/
          rsync -av --delete /var/www/cvforge-source/frontend/ /var/www/cvforge/
        
          cd /var/www/cvforgebackend/
          source .venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart cvforgeapi
        
          cd /var/www/cvforge/
          sudo systemctl restart nginx
